
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbTest?useSSL=false
    username: root
    password: zb301522
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1
server:
  port: 8080
  servlet:
    session:
      timeout: 7200
logging:
  config: classpath:logging-config.xml
  logDir: /Users/zhangcong/IdeaProjects/lostandfind/log
  logName: lostAndFind
mybatis:
  mapper-locations: classpath:/mybatis/*Mapper.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.lostandfind.mysql # 注意：对应实体类的路径
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
appId:
  xautId: wxc8c90d2d684c76a0
  yinghuo: wx7bc3d60d3ad76df5
appSecret:
  xautId: 7f24acb9cb4cf67e2fd57993032de4dc
  yinghuo: 5568743ce27e6d0897425ba23e568ef1
