
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbLAF?useSSL=false
    username: root
    password: zb301522
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081